_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
                - 106
            "2":
                - 1
                - 41
                - 106
            "3":
                - 7
                - 13
                - 55
                - 66
            "4": 3.11.9
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
AR:
    value: '[ 1  1  1  1  4  4  4  4 10 10 10 10 25 25 25 25]'
L:
    value: 32
W:
    value: '[11 11 11 11 11 11 11 11 21 21 21 21 41 41 41 41]'
model_type:
    value: exp
switch_epoch:
    value: 25
